; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:movelite]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps = 
	pololu/VL53L0X @ ^1.3.1
	esphome/ESPAsyncWebServer-esphome @ ^3.1.0
	me-no-dev/AsyncTCP @ ^1.1.1
	bblanchon/ArduinoJson @ ^6.21.3
	askuric/Simple FOC@2.3.3
board_build.filesystem = littlefs
board_build.f_cpu = 240000000L
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
	-DCORE_DEBUG_LEVEL=0
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=0
	-DMAP_WIDTH=100
	-DMAP_HEIGHT=100
	-DMAP_RESOLUTION=0.10f
	-DROBOT_WHEEL_RADIUS=0.035f
	-DROBOT_WHEEL_BASE=0.15f
	-DM0_UH=32 -DM0_VH=33 -DM0_WH=25 -DM0_EN=22
	-DM1_UH=26 -DM1_VH=27 -DM1_WH=14 -DM1_EN=12
	-DI2C0_SDA=19 -DI2C0_SCL=18
	-DI2C1_SDA=23 -DI2C1_SCL=5
	-DTOF_FRONT_XSHUT=4
	-DTOF_REAR_XSHUT=2
	-DTOF_FRONT_ADDR=0x30
	-DTOF_REAR_ADDR=0x31
upload_speed = 921600
